package com.coderedrobotics.scouting;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Michael
 */
public class GUI extends javax.swing.JFrame {

    private int made = 0, missed = 0;
    private Network network;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        autoRoughTerrain = new javax.swing.JCheckBox();
        autoReach = new javax.swing.JCheckBox();
        autoLowBar = new javax.swing.JCheckBox();
        autoLowGoal = new javax.swing.JCheckBox();
        autoHighGoal = new javax.swing.JCheckBox();
        autoPortcullis = new javax.swing.JCheckBox();
        autoChivalDeFrise = new javax.swing.JCheckBox();
        autoMoat = new javax.swing.JCheckBox();
        autoRamparts = new javax.swing.JCheckBox();
        autoDrawBridge = new javax.swing.JCheckBox();
        autoSallyPort = new javax.swing.JCheckBox();
        autoRockWall = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notes = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lowBar = new javax.swing.JCheckBox();
        roughTerrain = new javax.swing.JCheckBox();
        rockWall = new javax.swing.JCheckBox();
        sallyPort = new javax.swing.JCheckBox();
        drawBridge = new javax.swing.JCheckBox();
        ramparts = new javax.swing.JCheckBox();
        moat = new javax.swing.JCheckBox();
        chivalDeFrise = new javax.swing.JCheckBox();
        portcullis = new javax.swing.JCheckBox();
        lowGoal = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        challenge = new javax.swing.JCheckBox();
        attempedScale = new javax.swing.JCheckBox();
        successfullyScaledTower = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        speed = new javax.swing.JTextField();
        madeHighGoal = new javax.swing.JButton();
        missedHighGoal = new javax.swing.JButton();
        highGoalsMadeSpinner = new javax.swing.JSpinner();
        highGoalsMissedSpinner = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        broken = new javax.swing.JCheckBox();
        doesntFollowGameRules = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        ip = new javax.swing.JTextField();
        connectButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        team = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        port = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("2016 Scouting");

        jPanel2.setBackground(new java.awt.Color(255, 255, 0));

        autoRoughTerrain.setBackground(new java.awt.Color(255, 255, 0));
        autoRoughTerrain.setText("Rough Terrain");

        autoReach.setBackground(new java.awt.Color(255, 255, 0));
        autoReach.setText("Reach");

        autoLowBar.setBackground(new java.awt.Color(255, 255, 0));
        autoLowBar.setText("Low Bar");

        autoLowGoal.setBackground(new java.awt.Color(255, 255, 0));
        autoLowGoal.setText("Low Goal");

        autoHighGoal.setBackground(new java.awt.Color(255, 255, 0));
        autoHighGoal.setText("High Goal");

        autoPortcullis.setBackground(new java.awt.Color(255, 255, 0));
        autoPortcullis.setText("Portcullis");

        autoChivalDeFrise.setBackground(new java.awt.Color(255, 255, 0));
        autoChivalDeFrise.setText("Chival De Frise");

        autoMoat.setBackground(new java.awt.Color(255, 255, 0));
        autoMoat.setText("Moat");

        autoRamparts.setBackground(new java.awt.Color(255, 255, 0));
        autoRamparts.setText("Ramparts");

        autoDrawBridge.setBackground(new java.awt.Color(255, 255, 0));
        autoDrawBridge.setText("Drawbridge");

        autoSallyPort.setBackground(new java.awt.Color(255, 255, 0));
        autoSallyPort.setText("Sally Port");

        autoRockWall.setBackground(new java.awt.Color(255, 255, 0));
        autoRockWall.setText("Rock Wall");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("AUTO");

        jSeparator1.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(autoSallyPort)
                            .addComponent(autoRockWall)
                            .addComponent(autoRoughTerrain)
                            .addComponent(autoLowBar)
                            .addComponent(autoRamparts)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(autoChivalDeFrise, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(autoMoat))
                            .addComponent(autoDrawBridge)
                            .addComponent(autoPortcullis))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(autoHighGoal)
                            .addComponent(autoLowGoal)
                            .addComponent(autoReach))
                        .addGap(277, 277, 277))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addComponent(autoReach)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autoLowGoal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autoHighGoal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoPortcullis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autoChivalDeFrise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autoMoat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autoRamparts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autoDrawBridge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autoSallyPort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autoRockWall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autoRoughTerrain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(autoLowBar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NOTES");

        notes.setColumns(20);
        notes.setRows(5);
        jScrollPane1.setViewportView(notes);

        jPanel3.setBackground(new java.awt.Color(77, 166, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TELEOP");

        lowBar.setBackground(new java.awt.Color(255, 255, 0));
        lowBar.setText("Low Bar");
        lowBar.setOpaque(false);

        roughTerrain.setBackground(new java.awt.Color(255, 255, 0));
        roughTerrain.setText("Rough Terrain");
        roughTerrain.setOpaque(false);

        rockWall.setBackground(new java.awt.Color(255, 255, 0));
        rockWall.setText("Rock Wall");
        rockWall.setOpaque(false);

        sallyPort.setBackground(new java.awt.Color(255, 255, 0));
        sallyPort.setText("Sally Port");
        sallyPort.setOpaque(false);

        drawBridge.setBackground(new java.awt.Color(255, 255, 0));
        drawBridge.setText("Drawbridge");
        drawBridge.setOpaque(false);

        ramparts.setBackground(new java.awt.Color(255, 255, 0));
        ramparts.setText("Ramparts");
        ramparts.setOpaque(false);

        moat.setBackground(new java.awt.Color(255, 255, 0));
        moat.setText("Moat");
        moat.setOpaque(false);

        chivalDeFrise.setBackground(new java.awt.Color(255, 255, 0));
        chivalDeFrise.setText("Chival De Frise");
        chivalDeFrise.setOpaque(false);

        portcullis.setBackground(new java.awt.Color(255, 255, 0));
        portcullis.setText("Portcullis");
        portcullis.setOpaque(false);

        lowGoal.setText("Low Goal");
        lowGoal.setOpaque(false);

        jSeparator2.setBackground(new java.awt.Color(77, 166, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ENDGAME");

        challenge.setForeground(new java.awt.Color(255, 255, 255));
        challenge.setText("Challenge");
        challenge.setOpaque(false);

        attempedScale.setForeground(new java.awt.Color(255, 255, 255));
        attempedScale.setText("Attempted Scale");
        attempedScale.setOpaque(false);

        successfullyScaledTower.setForeground(new java.awt.Color(255, 255, 255));
        successfullyScaledTower.setText("Successfully Scaled Tower");
        successfullyScaledTower.setOpaque(false);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Speed:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(successfullyScaledTower)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(speed, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(attempedScale)
                    .addComponent(challenge))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(challenge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(attempedScale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(successfullyScaledTower)
                    .addComponent(jLabel5)
                    .addComponent(speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        madeHighGoal.setBackground(new java.awt.Color(0, 255, 0));
        madeHighGoal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        madeHighGoal.setText("<html><center><p>MADE HIGH GOAL</p></center></html>");
        madeHighGoal.setOpaque(false);
        madeHighGoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                madeHighGoalActionPerformed(evt);
            }
        });

        missedHighGoal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        missedHighGoal.setText("<html><center><p>MISSED HIGH GOAL</p></center></html>");
        missedHighGoal.setOpaque(false);
        missedHighGoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                missedHighGoalActionPerformed(evt);
            }
        });

        jLabel8.setText("Made");

        jLabel9.setText("Missed");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sallyPort)
                            .addComponent(rockWall)
                            .addComponent(roughTerrain)
                            .addComponent(lowBar)
                            .addComponent(ramparts)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chivalDeFrise, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(moat))
                            .addComponent(drawBridge)
                            .addComponent(portcullis))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lowGoal)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(highGoalsMadeSpinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                                    .addComponent(highGoalsMissedSpinner, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(madeHighGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(missedHighGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lowGoal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(highGoalsMadeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(highGoalsMissedSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(madeHighGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(missedHighGoal, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(portcullis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chivalDeFrise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ramparts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(drawBridge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sallyPort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rockWall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roughTerrain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lowBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        broken.setText("Broken");

        doesntFollowGameRules.setText("Doesn't follow game rules");

        jLabel6.setText("IP:");

        connectButton.setText("Connect");
        connectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Team:");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        jLabel10.setText("Port:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(doesntFollowGameRules)
                                    .addComponent(broken))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(team, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(port)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addGap(69, 69, 69))
                            .addComponent(connectButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(broken)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doesntFollowGameRules)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(connectButton)
                .addGap(293, 293, 293)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(team, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
        if (network == null) {
            try {
                network = new Network(ip.getText(), Integer.parseInt(port.getText()));
                ip.setEnabled(false);
                connectButton.setEnabled(false);
                port.setEnabled(false);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Could not connect", "IOException", JOptionPane.ERROR_MESSAGE);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "That is not a valid port number", "NumberFormatException", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_connectButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if (network != null) {
            try {
                network.sendData(autoReach.isSelected(), autoLowGoal.isSelected(),
                        autoHighGoal.isSelected(), autoPortcullis.isSelected(),
                        autoChivalDeFrise.isSelected(), autoMoat.isSelected(),
                        autoRamparts.isSelected(), autoDrawBridge.isSelected(),
                        autoSallyPort.isSelected(), autoRockWall.isSelected(),
                        autoRoughTerrain.isSelected(), autoLowBar.isSelected(),
                        lowGoal.isSelected(), made, missed, portcullis.isSelected(),
                        chivalDeFrise.isSelected(), moat.isSelected(), ramparts.isSelected(),
                        drawBridge.isSelected(), sallyPort.isSelected(), rockWall.isSelected(),
                        roughTerrain.isSelected(), lowBar.isSelected(), challenge.isSelected(),
                        attempedScale.isSelected(), successfullyScaledTower.isSelected(),
                        !"".equals(speed.getText()) ? Integer.parseInt(speed.getText()) : 0, broken.isSelected(),
                        doesntFollowGameRules.isSelected(), notes.getText(),
                        Integer.parseInt(team.getText()));
                autoReach.setSelected(false);
                autoLowGoal.setSelected(false);
                autoHighGoal.setSelected(false);
                autoPortcullis.setSelected(false);
                autoChivalDeFrise.setSelected(false);
                autoMoat.setSelected(false);
                autoRamparts.setSelected(false);
                autoDrawBridge.setSelected(false);
                autoSallyPort.setSelected(false);
                autoRockWall.setSelected(false);
                autoRoughTerrain.setSelected(false);
                autoLowBar.setSelected(false);
                lowGoal.setSelected(false);
                made = 0;
                highGoalsMadeSpinner.setValue(0);
                highGoalsMissedSpinner.setValue(0);
                portcullis.setSelected(false);
                chivalDeFrise.setSelected(false);
                moat.setSelected(false);
                ramparts.setSelected(false);
                drawBridge.setSelected(false);
                sallyPort.setSelected(false);
                rockWall.setSelected(false);
                roughTerrain.setSelected(false);
                lowBar.setSelected(false);
                challenge.setSelected(false);
                attempedScale.setSelected(false);
                successfullyScaledTower.setSelected(false);
                speed.setText("");
                notes.setText("");
                broken.setSelected(false);
                doesntFollowGameRules.setSelected(false);
                team.setText("");
            } catch (IOException ex) {
                ip.setEnabled(true);
                connectButton.setEnabled(true);
                port.setEnabled(true);
                JOptionPane.showMessageDialog(this, "Could not send the data", "IOException", JOptionPane.ERROR_MESSAGE);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Either your scale speed or team number is not a number."
                        + "\nI'm too lazy to figure out which it is so good luck", "NumberFormatException", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void madeHighGoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_madeHighGoalActionPerformed
        made = (int) highGoalsMadeSpinner.getValue() + 1;
        highGoalsMadeSpinner.setValue(made);
    }//GEN-LAST:event_madeHighGoalActionPerformed

    private void missedHighGoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_missedHighGoalActionPerformed
        missed = (int) highGoalsMissedSpinner.getValue() + 1;
        highGoalsMissedSpinner.setValue(missed);
    }//GEN-LAST:event_missedHighGoalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the System Default look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox attempedScale;
    private javax.swing.JCheckBox autoChivalDeFrise;
    private javax.swing.JCheckBox autoDrawBridge;
    private javax.swing.JCheckBox autoHighGoal;
    private javax.swing.JCheckBox autoLowBar;
    private javax.swing.JCheckBox autoLowGoal;
    private javax.swing.JCheckBox autoMoat;
    private javax.swing.JCheckBox autoPortcullis;
    private javax.swing.JCheckBox autoRamparts;
    private javax.swing.JCheckBox autoReach;
    private javax.swing.JCheckBox autoRockWall;
    private javax.swing.JCheckBox autoRoughTerrain;
    private javax.swing.JCheckBox autoSallyPort;
    private javax.swing.JCheckBox broken;
    private javax.swing.JCheckBox challenge;
    private javax.swing.JCheckBox chivalDeFrise;
    private javax.swing.JButton connectButton;
    private javax.swing.JCheckBox doesntFollowGameRules;
    private javax.swing.JCheckBox drawBridge;
    private javax.swing.JSpinner highGoalsMadeSpinner;
    private javax.swing.JSpinner highGoalsMissedSpinner;
    private javax.swing.JTextField ip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JCheckBox lowBar;
    private javax.swing.JCheckBox lowGoal;
    private javax.swing.JButton madeHighGoal;
    private javax.swing.JButton missedHighGoal;
    private javax.swing.JCheckBox moat;
    private javax.swing.JTextArea notes;
    private javax.swing.JTextField port;
    private javax.swing.JCheckBox portcullis;
    private javax.swing.JCheckBox ramparts;
    private javax.swing.JCheckBox rockWall;
    private javax.swing.JCheckBox roughTerrain;
    private javax.swing.JCheckBox sallyPort;
    private javax.swing.JTextField speed;
    private javax.swing.JButton submitButton;
    private javax.swing.JCheckBox successfullyScaledTower;
    private javax.swing.JTextField team;
    // End of variables declaration//GEN-END:variables
}
